# Generated by Django 4.2 on 2025-03-01 07:43

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='design',
            options={'ordering': ['-create_time'], 'verbose_name': '设计图', 'verbose_name_plural': '设计图'},
        ),
        migrations.AlterField(
            model_name='design',
            name='download',
            field=models.FileField(upload_to=user.models.user_design_file_path, verbose_name='下载链接'),
        ),
        migrations.AlterField(
            model_name='design',
            name='image',
            field=models.ImageField(upload_to=user.models.user_design_image_path, verbose_name='设计图图片'),
        ),
    ]
