"""
Django settings for equestrian project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os
from urllib.parse import urlparse
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 加载 .env 文件
load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# 默认关闭调试；本地开发请在 .env 中显式设置 DJANGO_DEBUG=true。
DEBUG = os.environ.get("DJANGO_DEBUG", "False").strip().lower() == "true"

# SECURITY WARNING: keep the secret key used in production secret!
# Security fix: SECRET_KEY must be strong and non-empty in production
def _is_secure_secret_key(value):
    """判断密钥是否满足 Django 生产环境的最小安全要求。"""
    return (
        len(value) >= 50
        and len(set(value)) >= 5
        and not value.startswith("django-insecure-")
    )


SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "").strip()
if not SECRET_KEY:
    if DEBUG:
        # Development fallback — never use this in production
        SECRET_KEY = "django-insecure-dev-only-do-not-use-in-production"
    else:
        raise ValueError("SECRET_KEY must be set in production (DJANGO_SECRET_KEY env var)")
elif not DEBUG and not _is_secure_secret_key(SECRET_KEY):
    raise ValueError(
        "DJANGO_SECRET_KEY must be at least 50 characters, contain at least "
        "5 unique characters, and not start with 'django-insecure-' in production"
    )

# Security fix: ALLOWED_HOSTS must not be wildcard in production
allowed_hosts_env = os.environ.get("DJANGO_ALLOWED_HOSTS", "")
ALLOWED_HOSTS = [item.strip() for item in allowed_hosts_env.split(",") if item.strip()]
if not ALLOWED_HOSTS or (len(ALLOWED_HOSTS) == 1 and ALLOWED_HOSTS[0] == ""):
    if DEBUG:
        # Development: allow localhost and common local networks
        ALLOWED_HOSTS = ["localhost", "127.0.0.1", "0.0.0.0"]
    else:
        # Production: require explicit ALLOWED_HOSTS
        raise ValueError(
            "ALLOWED_HOSTS must be set in production (DJANGO_ALLOWED_HOSTS env var)"
        )
if not DEBUG and "*" in ALLOWED_HOSTS:
    raise ValueError("DJANGO_ALLOWED_HOSTS must not contain '*' in production")

# Application definition

INSTALLED_APPS = [
    "simpleui",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework_simplejwt.token_blacklist",
    "rest_framework",
    "drf_spectacular",
    "corsheaders",
    "channels",
    "user.apps.UserConfig",
    "feedback",  # 新增反馈应用
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # 紧接 SecurityMiddleware
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "user.middleware.EnforceCSRFMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "user.middleware.TokenAuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "equestrian.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "equestrian.wsgi.application"

ASGI_APPLICATION = "equestrian.asgi.application"

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.environ.get("DB_NAME", "equestrian"),
        "USER": os.environ.get("DB_USER", "root"),
        "PASSWORD": os.environ.get("DB_PASSWORD", ""),
        "HOST": os.environ.get("DB_HOST", "127.0.0.1"),
        "PORT": os.environ.get("DB_PORT", "3306"),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "zh-hans"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# Media files
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"
# 上传和解析资源上限：设计图片 10MB、路线 JSON 2MB，预留表单字段空间。
DATA_UPLOAD_MAX_MEMORY_SIZE = 16 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 12 * 1024 * 1024
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000

# 站点域名配置，用于媒体文件 URL 和支付回调 URL 生成。
def _parse_http_url(value, setting_name, *, allow_path):
    """校验外部 URL，拒绝用户信息、查询串、片段和非法端口。"""
    parsed = urlparse(value)
    try:
        port = parsed.port
    except ValueError as exc:
        raise ValueError(f"{setting_name} must use a valid port") from exc

    if (
        parsed.scheme not in {"http", "https"}
        or not parsed.hostname
        or parsed.username is not None
        or parsed.password is not None
        or any(char.isspace() for char in parsed.netloc)
        or parsed.params
        or parsed.query
        or parsed.fragment
        or (not allow_path and parsed.path)
        or (port is not None and not 1 <= port <= 65535)
    ):
        raise ValueError(f"{setting_name} must be a valid HTTP(S) URL")
    return parsed


USE_HTTPS = os.environ.get("USE_HTTPS", "False").strip().lower() == "true"
SITE_DOMAIN = os.environ.get("SITE_DOMAIN", "localhost:8000").strip().rstrip("/")
if SITE_DOMAIN.startswith(("http://", "https://")):
    SITE_BASE_URL = SITE_DOMAIN
else:
    SITE_BASE_URL = f"{'https' if USE_HTTPS else 'http'}://{SITE_DOMAIN}"
if not DEBUG and not USE_HTTPS:
    raise ValueError("USE_HTTPS must be true in production")
parsed_site_url = _parse_http_url(SITE_BASE_URL, "SITE_DOMAIN", allow_path=False)
if not DEBUG and parsed_site_url.scheme != "https":
    raise ValueError("SITE_DOMAIN must use HTTPS in production")

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# 隐藏右侧SimpleUI广告链接和使用分析
SIMPLEUI_HOME_INFO = False
SIMPLEUI_ANALYSIS = False

# SIMPLEUI_HOME_QUICK = False
SIMPLEUI_HOME_ACTION = False

SIMPLEUI_INDEX = "https://kaliluying.github.io/"

SIMPLEUI_HOME_PAGE = "/api/feedback/dashboard"

# DRF配置
REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "EXCEPTION_HANDLER": "user.utils.api_exception_handler",
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "user.authentication.CookieJWTAuthentication",
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 9,  # 每页显示9条记录
    "DEFAULT_THROTTLE_RATES": {
        "login": "5/minute",
        "register": "5/hour",
        "password_reset": "3/hour",
        "ai": "10/minute",
        "payment_query": "30/minute",
        "feedback": "5/hour",
        "share_link": "20/hour",
        "export": "10/minute",
    },
}

SPECTACULAR_SETTINGS = {
    "TITLE": "马术障碍赛路线设计器 API",
    "DESCRIPTION": "路线设计、用户、会员、支付、AI 生成、反馈和协作接口",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
}

# Custom authentication backends for cookie-based JWT auth
AUTHENTICATION_BACKENDS = [
    "user.backends.CookieAuthBackend",
    "django.contrib.auth.backends.ModelBackend",
]

# JWT配置
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=14),
    "ROTATE_REFRESH_TOKENS": True,  # 开启刷新令牌自动更新
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    "AUDIENCE": None,
    "ISSUER": None,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
}

# CSRF配置 - Security fix: enforce secure settings in production
CSRF_COOKIE_SECURE = False if DEBUG else True  # 生产环境必须为True
CSRF_COOKIE_HTTPONLY = True  # 防止JavaScript访问CSRF cookie
CSRF_COOKIE_SAMESITE = "Lax"  # 允许跨站请求携带cookie
csrf_origins_env = os.environ.get("CSRF_TRUSTED_ORIGINS", "")
CSRF_TRUSTED_ORIGINS = (
    [item.strip() for item in csrf_origins_env.split(",") if item.strip()]
    if not DEBUG
    else [
        # Development trusted origins
        "http://localhost:5173",
        "http://127.0.0.1:5173",
        "http://localhost:8080",
        "http://127.0.0.1:8080",
        "http://192.168.1.6:5173",
        "http://192.168.1.6:8080",
        "https://equestrian.top",
        "http://192.168.1.7:5173",
        "http://192.168.1.7:8080",
        "http://192.168.1.2:5173",
    ]
)
if not CSRF_TRUSTED_ORIGINS or (
    len(CSRF_TRUSTED_ORIGINS) == 1 and CSRF_TRUSTED_ORIGINS[0] == ""
):
    if not DEBUG:
        raise ValueError("CSRF_TRUSTED_ORIGINS must be set in production")

# CORS配置 - Security fix: use allowlist instead of allow-all
CORS_ORIGIN_ALLOW_ALL = False  # 禁止所有来源，改用白名单
cors_origins_env = os.environ.get("CORS_ALLOWED_ORIGINS", "")
CORS_ALLOWED_ORIGINS = (
    [item.strip() for item in cors_origins_env.split(",") if item.strip()]
    if not DEBUG
    else [
        # Development CORS origins (localhost + local network)
        "http://localhost:5173",
        "http://127.0.0.1:5173",
        "http://localhost:8080",
        "http://127.0.0.1:8080",
        "http://192.168.1.6:5173",
        "http://192.168.1.6:8080",
        "https://equestrian.top",
        "http://192.168.1.7:5173",
        "http://192.168.1.7:8080",
        "http://192.168.1.2:5173",
    ]
)
if not CORS_ALLOWED_ORIGINS or (
    len(CORS_ALLOWED_ORIGINS) == 1 and CORS_ALLOWED_ORIGINS[0] == ""
):
    if not DEBUG:
        raise ValueError("CORS_ALLOWED_ORIGINS must be set in production")

# 允许跨域请求携带cookie
CORS_ALLOW_CREDENTIALS = True

# 支付宝服务器回调不携带浏览器 CSRF token，安全性由支付宝签名、订单和金额
# 校验负责；除此之外的所有修改型请求都必须通过 CSRF 校验。
CSRF_EXEMPT_PATHS = ("/user/api/payment/alipay/notify/",)

SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"
SECURE_REFERRER_POLICY = "same-origin"
SECURE_SSL_REDIRECT = os.environ.get(
    "DJANGO_SECURE_SSL_REDIRECT", str(not DEBUG)
).strip().lower() == "true"
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG

# 允许的HTTP方法
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

# 允许的HTTP头
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

# 前端 URL 配置；生产环境必须显式使用 HTTPS，避免密码重置链接指向本地或明文地址。
FRONTEND_URL = os.environ.get(
    "FRONTEND_URL",
    "http://localhost:5173" if DEBUG else "",
).strip().rstrip("/")
if not FRONTEND_URL:
    raise ValueError("FRONTEND_URL must be set in production")
parsed_frontend_url = _parse_http_url(FRONTEND_URL, "FRONTEND_URL", allow_path=True)
if not DEBUG and parsed_frontend_url.scheme != "https":
    raise ValueError("FRONTEND_URL must use HTTPS in production")


# 邮件配置
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"  # 默认的SMTP后端
EMAIL_HOST = "smtp.gmail.com"  # Gmail SMTP服务器地址
EMAIL_PORT = 587  # TLS加密端口
EMAIL_USE_TLS = True  # 启用TLS加密
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")  # 你的Gmail邮箱地址
EMAIL_HOST_PASSWORD = os.environ.get(
    "EMAIL_HOST_PASSWORD", ""
)  # 应用专用密码（非邮箱登录密码）


# settings.py
REDIS_URL = os.environ.get("REDIS_URL", "redis://127.0.0.1:6379/0")
CACHE_REDIS_URL = os.environ.get("CACHE_REDIS_URL", "redis://127.0.0.1:6379/1")

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [REDIS_URL],
        },
    },
}

# 缓存配置 - 复用 Redis，用于 WebSocket 协作状态等
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": CACHE_REDIS_URL,
    },
}


# 创建日志目录
LOGS_DIR = os.path.join(BASE_DIR, "logs")
os.makedirs(LOGS_DIR, exist_ok=True)

# 日志配置
LOG_LEVEL = "DEBUG" if DEBUG else "INFO"
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "level": LOG_LEVEL,
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "file": {
            "level": LOG_LEVEL,
            "class": "logging.FileHandler",
            "filename": os.path.join(LOGS_DIR, "django-channels.log"),
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],  # 同时输出到控制台和文件
            "level": "INFO",
            "propagate": True,
        },
        "django.channels": {
            "handlers": ["console", "file"],  # 同时输出到控制台和文件
            "level": "DEBUG" if DEBUG else "WARNING",
            "propagate": False,
        },
    },
}

# 支付宝配置
ALIPAY_APPID = os.environ.get("ALIPAY_APPID", "")  # 替换为实际的支付宝应用ID
ALIPAY_SELLER_ID = os.environ.get("ALIPAY_SELLER_ID", "")  # 支付宝商户号
ALIPAY_APP_PRIVATE_KEY_PATH = os.path.join(
    BASE_DIR, "equestrian/keys/app_private_key.pem"
)
ALIPAY_ALIPAY_PUBLIC_KEY_PATH = os.path.join(
    BASE_DIR, "equestrian/keys/alipay_public_key.pem"
)
ALIPAY_NOTIFY_URL = f"{SITE_BASE_URL}/user/api/payment/alipay/notify/"
ALIPAY_RETURN_URL = f"{SITE_BASE_URL}/user/payment/success/"
ALIPAY_DEBUG = os.environ.get("ALIPAY_DEBUG", str(DEBUG)).strip().lower() == "true"
