# Generated by Django 4.2 on 2025-03-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=6, verbose_name='月度会员价格'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='yearly_price',
            field=models.DecimalField(decimal_places=2, default=150.0, max_digits=6, verbose_name='年度会员价格'),
        ),
    ]
