# Generated by Django 4.2 on 2025-03-05 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_userprofile_monthly_price_userprofile_yearly_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='会员计划名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='会员计划代码')),
                ('monthly_price', models.DecimalField(decimal_places=2, default=15.0, max_digits=6, verbose_name='月度价格')),
                ('yearly_price', models.DecimalField(decimal_places=2, default=150.0, max_digits=6, verbose_name='年度价格')),
                ('storage_limit', models.PositiveIntegerField(default=100, verbose_name='存储限制(设计数量)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='会员计划描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '会员计划',
                'verbose_name_plural': '会员计划',
                'ordering': ['monthly_price'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='membership_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='user.membershipplan', verbose_name='会员计划'),
        ),
    ]
