# Generated by Django 4.2 on 2025-03-05 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_membershipplan_userprofile_membership_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='monthly_price',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='yearly_price',
        ),
    ]
