# Generated by Django 4.2 on 2025-03-05 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_userprofile_monthly_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='design_storage_limit',
        ),
    ]
