# Generated by Django 4.2 on 2025-03-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_customobstacle'),
    ]

    operations = [
        migrations.AddField(
            model_name='customobstacle',
            name='is_shared',
            field=models.BooleanField(default=False, verbose_name='是否共享'),
        ),
    ]
