# Generated by Django 4.2 on 2025-03-10 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_membershiporder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='premium_expiry',
            new_name='premium_expire_date',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pending_membership_expire_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='待生效会员过期时间'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pending_membership_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_users', to='user.membershipplan', verbose_name='待生效会员计划'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pending_membership_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='待生效会员开始时间'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='storage_limit',
            field=models.PositiveIntegerField(default=5, verbose_name='存储限制(设计数量)'),
        ),
    ]
