# Generated by Django 4.2 on 2025-03-15 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0014_design_collaborators_alter_design_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='collaborators',
        ),
        migrations.AlterField(
            model_name='design',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
    ]
