# Generated by Django 5.1.3 on 2026-01-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_remove_design_collaborators_alter_design_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='custom_obstacle_limit',
            field=models.PositiveIntegerField(blank=True, help_text='null表示无限制', null=True, verbose_name='自定义障碍物限制(个)'),
        ),
    ]
