# Generated by Django 5.1.3 on 2026-03-01 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_membershipplan_custom_obstacle_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGenerationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(verbose_name='用户输入')),
                ('result', models.JSONField(blank=True, null=True, verbose_name='生成结果')),
                ('token_used', models.PositiveIntegerField(default=0, verbose_name='消耗token数')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='成本')),
                ('status', models.CharField(choices=[('pending', '处理中'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_histories', to='user.userprofile', verbose_name='用户资料')),
            ],
            options={
                'verbose_name': 'AI生成历史',
                'verbose_name_plural': 'AI生成历史',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIGenerationQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_quota', models.PositiveIntegerField(default=3, verbose_name='免费配额')),
                ('purchased_quota', models.PositiveIntegerField(default=0, verbose_name='购买配额')),
                ('used_quota', models.PositiveIntegerField(default=0, verbose_name='已使用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_quota', to='user.userprofile', verbose_name='用户资料')),
            ],
            options={
                'verbose_name': 'AI生成配额',
                'verbose_name_plural': 'AI生成配额',
            },
        ),
    ]
