# Generated by Django 5.1.3 on 2026-03-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_aigenerationhistory_aigenerationquota'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='aigenerationhistory',
            index=models.Index(fields=['-created_at'], name='user_aigene_created_234577_idx'),
        ),
    ]
