// Auto-generated from OpenAPI schema. Do not edit manually.
export const openApiVersion = "3.0.3"
export type ApiPath =
  | "/api/feedback/"
  | "/api/feedback/dashboard"
  | "/api/feedback/{id}/"
  | "/user/admin/analytics/"
  | "/user/ai/coach-notes/"
  | "/user/ai/edit-course/"
  | "/user/ai/generate/"
  | "/user/ai/history/"
  | "/user/ai/purchase/"
  | "/user/ai/quota/"
  | "/user/api/payment/alipay/notify/"
  | "/user/api/payment/create-order/"
  | "/user/api/payment/order-status/{order_id}/"
  | "/user/api/payment/orders/"
  | "/user/api/payment/orders/{order_id}/"
  | "/user/api/payment/orders/{order_id}/invoice/"
  | "/user/api/payment/orders/{order_id}/invoice/mark-issued/"
  | "/user/csrf/"
  | "/user/designs/"
  | "/user/designs/fix-course/"
  | "/user/designs/my/"
  | "/user/designs/shared/"
  | "/user/designs/validate-course/"
  | "/user/designs/{design_id}/share-link/"
  | "/user/designs/{id}/"
  | "/user/designs/{id}/asset/"
  | "/user/designs/{id}/collaboration-events/"
  | "/user/designs/{id}/comments/"
  | "/user/designs/{id}/comments/{comment_id}/resolve/"
  | "/user/designs/{id}/download/"
  | "/user/designs/{id}/like/"
  | "/user/designs/{id}/share/"
  | "/user/designs/{id}/toggle-share/"
  | "/user/designs/{id}/versions/"
  | "/user/designs/{id}/versions/{version_id}/"
  | "/user/designs/{id}/versions/{version_id}/copy/"
  | "/user/designs/{id}/versions/{version_id}/restore/"
  | "/user/forgot-password/"
  | "/user/login/"
  | "/user/logout/"
  | "/user/obstacles/"
  | "/user/obstacles/count/"
  | "/user/obstacles/shared/"
  | "/user/obstacles/{id}/"
  | "/user/obstacles/{id}/toggle-share/"
  | "/user/register/"
  | "/user/reset-password/"
  | "/user/templates/"
  | "/user/templates/{id}/"
  | "/user/templates/{id}/create-design/"
  | "/user/templates/{id}/favorite/"
  | "/user/token/refresh/"
  | "/user/users/"
  | "/user/users/change_email/"
  | "/user/users/change_password/"
  | "/user/users/check_premium/"
  | "/user/users/my_profile/"
  | "/user/users/{id}/"
  | "/user/users/{id}/set_premium/"

export interface GeneratedApiSummary {
  pathCount: number
}

export const generatedApiSummary: GeneratedApiSummary = {
  pathCount: 59,
}
