# Generated by Django 4.2 on 2025-03-08 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('feature', '功能建议'), ('bug', '问题报告'), ('ux', '用户体验'), ('other', '其他')], max_length=20, verbose_name='反馈类型')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(verbose_name='详细描述')),
                ('contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='联系方式')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('in_progress', '处理中'), ('resolved', '已解决'), ('closed', '已关闭')], default='pending', max_length=20, verbose_name='状态')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='管理员备注')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户反馈',
                'verbose_name_plural': '用户反馈',
                'ordering': ['-created_at'],
            },
        ),
    ]
